// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package proxy

import (
	"eGZ-Board/api/proxy"
)

type ControllerV1 struct{}

func NewV1() proxy.IProxyV1 {
	return &ControllerV1{}
}
