// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package count_down

import (
	"eGZ-Board/api/count_down"
)

type ControllerV1 struct{}

func NewV1() count_down.ICountDownV1 {
	return &ControllerV1{}
}
